version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ts"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
      - "typescript"

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "rust"
      